// Seed products — NR-11 (FINAL), 62 products across 7 categories.
//
// Regional mix: Western, Eastern, South-South, Northern.
// productType: "cooked" (fresh, same-day own-fleet/pickup) or "packaged" (3-4 days).
// stock is the seed quantity; runSeed.js creates matching Inventory batches.
//
// ⚠️ PRICES ARE NOT VERIFIED LIVE DATA. Nigerian food prices are volatile.
// Validate every price against real supplier/competitor data before launch.
// The structure (units, types, regional mix, portion logic) is sound; the numbers are not.

export default [
  // ---------------------------------------------------------------
  // CATEGORY 1: SWALLOWS (10)
  // ---------------------------------------------------------------
  {
    name: "Fufu/Akpu - Fresh",
    description:
      "Freshly pounded cassava fufu, soft and smooth. Best eaten the same day with any of our soups.",
    price: 500,
    unit: "portion",
    productType: "cooked",
    prepLeadTime: 2,
    maxDailyQty: 150,
    stock: 150,
    categoryName: "Swallows",
    region: "Western",
    tags: ["swallow", "fufu", "akpu", "cassava", "fresh"],
    isFeatured: true,
  },
  {
    name: "Amala - Fresh",
    description:
      "Rich, dark eloko amala pounded fresh. A Yoruba classic that pairs perfectly with ewedu and obe ata.",
    price: 500,
    unit: "portion",
    productType: "cooked",
    prepLeadTime: 2,
    maxDailyQty: 120,
    stock: 120,
    categoryName: "Swallows",
    region: "Western",
    tags: ["swallow", "amala", "eloko", "yoruba"],
    isFeatured: false,
  },
  {
    name: "Semo - Fresh",
    description:
      "Smooth semolina swallow, light on the stomach. A reliable choice for any soup.",
    price: 500,
    unit: "portion",
    productType: "cooked",
    prepLeadTime: 2,
    maxDailyQty: 130,
    stock: 130,
    categoryName: "Swallows",
    region: "Western",
    tags: ["swallow", "semo", "semolina"],
    isFeatured: false,
  },
  {
    name: "Pounded Yam - Fresh",
    description:
      "Properly pounded yam from fresh tubers, stretchy and never glutinous. Our most requested swallow.",
    price: 500,
    unit: "portion",
    productType: "cooked",
    prepLeadTime: 2,
    maxDailyQty: 100,
    stock: 100,
    categoryName: "Swallows",
    region: "Western",
    tags: ["swallow", "pounded yam", "yam", "fresh"],
    isFeatured: true,
  },
  {
    name: "Eba - Fresh",
    description:
      "Warm garri eba, turned fresh to the right firmness. A fast, filling staple.",
    price: 500,
    unit: "portion",
    productType: "cooked",
    prepLeadTime: 2,
    maxDailyQty: 140,
    stock: 140,
    categoryName: "Swallows",
    region: "Eastern",
    tags: ["swallow", "eba", "garri"],
    isFeatured: false,
  },
  {
    name: "Fufu Powder - Packaged",
    description:
      "Dry cassava fufu flour. Just add hot water and knead. Shelf-stable for months.",
    price: 1800,
    unit: "pack",
    productType: "packaged",
    stock: 300,
    categoryName: "Swallows",
    region: "Western",
    tags: ["swallow", "fufu", "powder", "packaged", "shelf-stable"],
    isFeatured: false,
  },
  {
    name: "Amala Lafun - Packaged",
    description:
      "Fine yam flour (lafun) for making amala at home. No lumps, easy to turn.",
    price: 1400,
    unit: "pack",
    productType: "packaged",
    stock: 280,
    categoryName: "Swallows",
    region: "Western",
    tags: ["swallow", "amala", "lafun", "yam flour", "packaged"],
    isFeatured: false,
  },
  {
    name: "Pounded Yam Powder - Packaged",
    description:
      "Instant pounded yam flour with the texture of freshly pounded yam.",
    price: 2200,
    unit: "pack",
    productType: "packaged",
    stock: 200,
    categoryName: "Swallows",
    region: "Western",
    tags: ["swallow", "pounded yam", "powder", "packaged"],
    isFeatured: false,
  },
  {
    name: "Semolina - Packaged",
    description:
      "Premium semolina for smooth, quick swallows. Cooks in minutes.",
    price: 1500,
    unit: "pack",
    productType: "packaged",
    stock: 260,
    categoryName: "Swallows",
    region: "Eastern",
    tags: ["swallow", "semolina", "semo", "packaged"],
    isFeatured: false,
  },
  {
    name: "Garri - Packaged",
    description:
      "Crisp, well-roasted garri. Ijebu style, slightly sour and perfect for eba or soaking.",
    price: 1100,
    unit: "pack",
    productType: "packaged",
    stock: 350,
    categoryName: "Swallows",
    region: "Western",
    tags: ["garri", "swallow", "packaged", "ijebu"],
    isFeatured: false,
  },

  // ---------------------------------------------------------------
  // CATEGORY 2: SOUPS & STEWS (11)
  // ---------------------------------------------------------------
  {
    name: "Obe Ata - Fresh",
    description:
      "Our signature red stew, slow-cooked from fresh bell peppers, onions and tomatoes. Rich, balanced heat. Packed in a 500ml tub, enough for 2 to 3 generous servings.",
    price: 1200,
    unit: "500ml",
    productType: "cooked",
    prepLeadTime: 3,
    maxDailyQty: 90,
    stock: 90,
    categoryName: "Soups & Stews",
    region: "Western",
    tags: ["soup", "stew", "obe ata", "red stew", "fresh"],
    isFeatured: true,
  },
  {
    name: "Gbegiri - Fresh",
    description:
      "Classic bean soup, smooth and hearty. Traditionally eaten alongside ewedu and obe ata as part of the Yoruba trio.",
    price: 1000,
    unit: "500ml",
    productType: "cooked",
    prepLeadTime: 3,
    maxDailyQty: 70,
    stock: 70,
    categoryName: "Soups & Stews",
    region: "Western",
    tags: ["soup", "gbegiri", "bean soup", "fresh", "side"],
    isFeatured: false,
  },
  {
    name: "Egusi Soup - Fresh",
    description:
      "Ground melon seed soup cooked with spinach and stockfish. Deep, nutty and filling. 500ml tub serves 2 to 3.",
    price: 1500,
    unit: "500ml",
    productType: "cooked",
    prepLeadTime: 3,
    maxDailyQty: 80,
    stock: 80,
    categoryName: "Soups & Stews",
    region: "Western",
    tags: ["soup", "egusi", "melon seed", "fresh"],
    isFeatured: true,
  },
  {
    name: "Egusi Soup Mix",
    description:
      "Dry ground egusi with blended spices and seasoning. Add your own proteins and vegetables. Lasts months sealed.",
    price: 2500,
    unit: "pack",
    productType: "packaged",
    stock: 220,
    categoryName: "Soups & Stews",
    region: "Western",
    tags: ["soup", "egusi", "mix", "packaged", "shelf-stable"],
    isFeatured: false,
  },
  {
    name: "Ogbono Soup - Fresh",
    description:
      "Draw soup made from ground ogbono seeds, cooked to the right stretchiness with tender leafy greens.",
    price: 1400,
    unit: "500ml",
    productType: "cooked",
    prepLeadTime: 3,
    maxDailyQty: 75,
    stock: 75,
    categoryName: "Soups & Stews",
    region: "Western",
    tags: ["soup", "ogbono", "draw soup", "fresh"],
    isFeatured: false,
  },
  {
    name: "Banga Soup - Fresh",
    description:
      "Niger Delta palm fruit soup, aromatic and rich. A South-South favourite best eaten with starch or fufu.",
    price: 1200,
    unit: "500ml",
    productType: "cooked",
    prepLeadTime: 3,
    maxDailyQty: 60,
    stock: 60,
    categoryName: "Soups & Stews",
    region: "South-South",
    tags: ["soup", "banga", "palm fruit", "south south", "fresh"],
    isFeatured: false,
  },
  {
    name: "Bitter Leaf Soup - Fresh",
    description:
      "Traditional Igbo bitter leaf soup, properly washed to mellow the bitterness and cooked slow with stock.",
    price: 1100,
    unit: "500ml",
    productType: "cooked",
    prepLeadTime: 3,
    maxDailyQty: 60,
    stock: 60,
    categoryName: "Soups & Stews",
    region: "Eastern",
    tags: ["soup", "bitter leaf", "igbo", "fresh"],
    isFeatured: false,
  },
  {
    name: "Okra Soup - Fresh",
    description:
      "Chunky fresh okra soup with palm oil and authentic seasoning. Not over-blended, just right.",
    price: 1000,
    unit: "500ml",
    productType: "cooked",
    prepLeadTime: 3,
    maxDailyQty: 70,
    stock: 70,
    categoryName: "Soups & Stews",
    region: "Eastern",
    tags: ["soup", "okra", "igbo", "fresh"],
    isFeatured: false,
  },
  {
    name: "Ewedu Soup - Fresh",
    description:
      "Slippery jute leaf soup, cooked the Yoruba way. Best paired with amala, obe ata and gbegiri.",
    price: 1000,
    unit: "500ml",
    productType: "cooked",
    prepLeadTime: 3,
    maxDailyQty: 65,
    stock: 65,
    categoryName: "Soups & Stews",
    region: "Western",
    tags: ["soup", "ewedu", "jute leaf", "yoruba", "fresh"],
    isFeatured: false,
  },
  {
    name: "Edikang Ikong - Fresh",
    description:
      "The luxury of Efik/Ibibio cuisine, packed with young pumpkin and fluted squash leaves.",
    price: 1500,
    unit: "500ml",
    productType: "cooked",
    prepLeadTime: 3,
    maxDailyQty: 50,
    stock: 50,
    categoryName: "Soups & Stews",
    region: "South-South",
    tags: ["soup", "edikang ikong", "efik", "ibibio", "fresh"],
    isFeatured: true,
  },
  {
    name: "Obe Ata Soup Mix",
    description:
      "Dry blended pepper and spice mix for making obe ata at home with your own tomatoes and proteins.",
    price: 2200,
    unit: "pack",
    productType: "packaged",
    stock: 240,
    categoryName: "Soups & Stews",
    region: "Western",
    tags: ["soup", "obe ata", "mix", "packaged", "shelf-stable"],
    isFeatured: false,
  },

  // ---------------------------------------------------------------
  // CATEGORY 3: SEASONINGS (8)
  // ---------------------------------------------------------------
  {
    name: "Ground Crayfish",
    description:
      "Finely ground smoked crayfish. The backbone of authentic Nigerian soup flavour.",
    price: 1800,
    unit: "pack",
    productType: "packaged",
    stock: 300,
    categoryName: "Seasonings",
    region: "South-South",
    tags: ["seasoning", "crayfish", "smoked"],
    isFeatured: false,
  },
  {
    name: "Locust Beans (Iru)",
    description:
      "Traditional fermented locust beans, washed and ready to cook. Deep umami for ewedu and obe ata.",
    price: 1500,
    unit: "pack",
    productType: "packaged",
    stock: 260,
    categoryName: "Seasonings",
    region: "Western",
    tags: ["seasoning", "iru", "locust bean", "fermented"],
    isFeatured: false,
  },
  {
    name: "Yaji Suya Spice",
    description:
      "House ground yaji blend for suya and grilled meats. Smoky, spicy and nut-forward.",
    price: 1200,
    unit: "pack",
    productType: "packaged",
    stock: 280,
    categoryName: "Seasonings",
    region: "Northern",
    tags: ["seasoning", "yaji", "suya", "spice", "northern"],
    isFeatured: false,
  },
  {
    name: "Ground Pepper (Ose)",
    description:
      "Hot dried pepper ground fine. Adjust your own heat level in any dish.",
    price: 1400,
    unit: "pack",
    productType: "packaged",
    stock: 290,
    categoryName: "Seasonings",
    region: "Eastern",
    tags: ["seasoning", "pepper", "ose", "spicy"],
    isFeatured: false,
  },
  {
    name: "Bouillon Cubes (Knorr) - Pack (50 x 8g)",
    description:
      "Bulk pack of 50 bouillon cubes, 8g each. The everyday seasoning for stocks, stews and marinades.",
    price: 950,
    unit: "pack",
    productType: "packaged",
    stock: 400,
    categoryName: "Seasonings",
    region: "Western",
    tags: ["seasoning", "bouillon", "knorr", "cubes", "packaged"],
    isFeatured: true,
  },
  {
    name: "Thyme Leaves",
    description:
      "Dried whole thyme. Aromatic and versatile for rice, stews and roasts.",
    price: 1100,
    unit: "pack",
    productType: "packaged",
    stock: 250,
    categoryName: "Seasonings",
    region: "Western",
    tags: ["seasoning", "thyme", "herb", "dried"],
    isFeatured: false,
  },
  {
    name: "Curry Powder",
    description:
      "Mild curry blend suited to Nigerian cooking. Earthy, not overpowering.",
    price: 1000,
    unit: "pack",
    productType: "packaged",
    stock: 250,
    categoryName: "Seasonings",
    region: "Western",
    tags: ["seasoning", "curry", "spice", "dried"],
    isFeatured: false,
  },
  {
    name: "Salt (Iodized)",
    description:
      "Fine iodized cooking salt. Kitchen essential.",
    price: 800,
    unit: "pack",
    productType: "packaged",
    stock: 500,
    categoryName: "Seasonings",
    region: "Eastern",
    tags: ["seasoning", "salt", "iodized", "essential"],
    isFeatured: false,
  },

  // ---------------------------------------------------------------
  // CATEGORY 4: OILS & FATS (4)
  // ---------------------------------------------------------------
  {
    name: "Palm Oil (Red)",
    description:
      "Unrefined red palm oil, boiled and settled. Rich colour and authentic taste for soups and stews. 1 litre bottle.",
    price: 3300,
    unit: "1 Litre",
    productType: "packaged",
    stock: 180,
    categoryName: "Oils & Fats",
    region: "South-South",
    tags: ["oil", "palm oil", "red oil", "cooking"],
    isFeatured: true,
  },
  {
    name: "Kings Groundnut Oil",
    description:
      "Cold-pressed groundnut oil with a clean, light flavour. High smoke point, good for frying. 1 litre bottle.",
    price: 3500,
    unit: "1 Litre",
    productType: "packaged",
    stock: 150,
    categoryName: "Oils & Fats",
    region: "Northern",
    tags: ["oil", "groundnut", "peanut oil", "cooking", "frying"],
    isFeatured: false,
  },
  {
    name: "Coconut Oil",
    description:
      "Pure expeller-pressed coconut oil, food grade. 500ml jar.",
    price: 13000,
    unit: "500ml",
    productType: "packaged",
    stock: 60,
    categoryName: "Oils & Fats",
    region: "South-South",
    tags: ["oil", "coconut oil", "premium"],
    isFeatured: false,
  },
  {
    name: "Shea Butter",
    description:
      "Raw unrefined shea butter, washed and whipped smooth. Food and cosmetic use. 250g tub.",
    price: 4000,
    unit: "250g",
    productType: "packaged",
    stock: 90,
    categoryName: "Oils & Fats",
    region: "Northern",
    tags: ["fat", "shea butter", "ori", "raw", "unrefined"],
    isFeatured: false,
  },

  // ---------------------------------------------------------------
  // CATEGORY 5: SNACKS (10)
  // ---------------------------------------------------------------
  {
    name: "Chin Chin",
    description:
      "Crispy fried snack cubes, lightly sweet and crunchy. Perfect with drinks. Packaged, stays crisp for weeks.",
    price: 1200,
    unit: "pack",
    productType: "packaged",
    stock: 280,
    categoryName: "Snacks",
    region: "Western",
    tags: ["snack", "chin chin", "packaged", "crunchy"],
    isFeatured: false,
  },
  {
    name: "Puff Puff - Fresh",
    description:
      "Golden, airy fried dough balls cooked to order. Best eaten the same day.",
    price: 1000,
    unit: "portion",
    productType: "cooked",
    prepLeadTime: 1,
    maxDailyQty: 100,
    stock: 100,
    categoryName: "Snacks",
    region: "Western",
    tags: ["snack", "puff puff", "fresh", "fried"],
    isFeatured: false,
  },
  {
    name: "Akara - Fresh",
    description:
      "Black-eyed pea bean fritters, crisp outside and soft inside. Deep-fried fresh per order.",
    price: 1000,
    unit: "portion",
    productType: "cooked",
    prepLeadTime: 1,
    maxDailyQty: 90,
    stock: 90,
    categoryName: "Snacks",
    region: "Western",
    tags: ["snack", "akara", "bean", "fresh", "fried"],
    isFeatured: true,
  },
  {
    name: "Meat Pie - Fresh",
    description:
      "Flaky shortcrust pie filled with minced beef, potato and carrot. Baked fresh daily.",
    price: 1200,
    unit: "portion",
    productType: "cooked",
    prepLeadTime: 4,
    maxDailyQty: 80,
    stock: 80,
    categoryName: "Snacks",
    region: "Western",
    tags: ["snack", "meat pie", "pastry", "fresh", "baked"],
    isFeatured: false,
  },
  {
    name: "Spring Rolls - Fresh",
    description:
      "Crisp vegetable and chicken spring rolls, fried to order.",
    price: 900,
    unit: "portion",
    productType: "cooked",
    prepLeadTime: 2,
    maxDailyQty: 90,
    stock: 90,
    categoryName: "Snacks",
    region: "Eastern",
    tags: ["snack", "spring rolls", "fresh", "fried"],
    isFeatured: false,
  },
  {
    name: "Plantain Chips",
    description:
      "Thin-sliced ripe plantain fried and lightly salted. Sealed pack stays crunchy.",
    price: 1500,
    unit: "pack",
    productType: "packaged",
    stock: 260,
    categoryName: "Snacks",
    region: "Western",
    tags: ["snack", "plantain chips", "dodo chips", "packaged"],
    isFeatured: false,
  },
  {
    name: "Kuli Kuli",
    description:
      "Crunchy groundnut snack, deep-roasted with ginger and pepper. Long shelf life.",
    price: 1300,
    unit: "pack",
    productType: "packaged",
    stock: 240,
    categoryName: "Snacks",
    region: "Northern",
    tags: ["snack", "kuli kuli", "groundnut", "packaged", "northern"],
    isFeatured: false,
  },
  {
    name: "Kilishi",
    description:
      "Northern air-dried spiced beef, thin and intensely flavoured. Packaged, keeps well.",
    price: 1800,
    unit: "pack",
    productType: "packaged",
    stock: 180,
    categoryName: "Snacks",
    region: "Northern",
    tags: ["snack", "kilishi", "dried meat", "northern", "packaged"],
    isFeatured: false,
  },
  {
    name: "Moi Moi - Fresh",
    description:
      "Steamed bean pudding with pepper, fish and egg. Soft, savoury and filling.",
    price: 950,
    unit: "portion",
    productType: "cooked",
    prepLeadTime: 3,
    maxDailyQty: 85,
    stock: 85,
    categoryName: "Snacks",
    region: "Western",
    tags: ["snack", "moi moi", "bean pudding", "fresh", "steamed"],
    isFeatured: false,
  },
  {
    name: "Boli & Groundnut - Fresh",
    description:
      "Slow-roasted plantain served with roasted groundnut. Smoky, sweet and salty.",
    price: 1100,
    unit: "portion",
    productType: "cooked",
    prepLeadTime: 1,
    maxDailyQty: 100,
    stock: 100,
    categoryName: "Snacks",
    region: "Western",
    tags: ["snack", "boli", "plantain", "groundnut", "fresh", "roasted"],
    isFeatured: true,
  },

  // ---------------------------------------------------------------
  // CATEGORY 6: DRINKS (5)
  // ---------------------------------------------------------------
  {
    name: "Zobo Drink",
    description:
      "Chilled hibiscus infusion brewed with ginger and pineapple. Refreshing and lightly tart. 500ml bottle.",
    price: 1500,
    unit: "500ml bottle",
    productType: "packaged",
    stock: 220,
    categoryName: "Drinks",
    region: "Northern",
    tags: ["drink", "zobo", "hibiscus", "juice", "chilled"],
    isFeatured: true,
  },
  {
    name: "Kunu Drink",
    description:
      "Classic Northern grain drink, smooth and lightly spiced. 500ml bottle.",
    price: 1400,
    unit: "500ml bottle",
    productType: "packaged",
    stock: 180,
    categoryName: "Drinks",
    region: "Northern",
    tags: ["drink", "kunu", "grain", "northern"],
    isFeatured: false,
  },
  {
    name: "Tiger Nut Drink",
    description:
      "Creamy kunun aya made from tiger nuts, dates and coconut. Naturally sweet, no added sugar. 500ml bottle.",
    price: 1600,
    unit: "500ml bottle",
    productType: "packaged",
    stock: 170,
    categoryName: "Drinks",
    region: "Northern",
    tags: ["drink", "tiger nut", "kunun aya", "creamy"],
    isFeatured: false,
  },
  {
    name: "Fresh Juice - Orange",
    description:
      "Freshly pressed orange juice with no added sugar or water. 500ml bottle.",
    price: 2000,
    unit: "500ml bottle",
    productType: "packaged",
    stock: 140,
    categoryName: "Drinks",
    region: "Western",
    tags: ["drink", "juice", "orange", "fresh"],
    isFeatured: false,
  },
  {
    name: "Fresh Juice - Special Blend (Orange, Pineapple)",
    description:
      "Our house blend of orange and pineapple, pressed fresh. 500ml bottle.",
    price: 2500,
    unit: "500ml bottle",
    productType: "packaged",
    stock: 130,
    categoryName: "Drinks",
    region: "Western",
    tags: ["drink", "juice", "special blend", "orange", "pineapple"],
    isFeatured: false,
  },

  // ---------------------------------------------------------------
  // CATEGORY 7: PROTEINS (14)
  // ---------------------------------------------------------------
  {
    name: "Stockfish (Dried)",
    description:
      "Premium dried stockfish (okporoko), properly cleaned and cut. Essential for authentic soups. 500g pack.",
    price: 3000,
    unit: "500g",
    productType: "packaged",
    stock: 150,
    categoryName: "Proteins",
    region: "South-South",
    tags: ["protein", "stockfish", "dried", "okporoko", "fish"],
    isFeatured: false,
  },
  {
    name: "Kika (Dried Fish)",
    description:
      "Sun-dried small fish, clean and well-preserved. Deep umami for soups. 500g pack.",
    price: 2500,
    unit: "500g",
    productType: "packaged",
    stock: 160,
    categoryName: "Proteins",
    region: "Northern",
    tags: ["protein", "kika", "dried fish", "asi"],
    isFeatured: false,
  },
  {
    name: "Dried Beef",
    description:
      "Air-dried beef strips, trimmed and clean. Long shelf life. 500g pack.",
    price: 3000,
    unit: "500g",
    productType: "packaged",
    stock: 120,
    categoryName: "Proteins",
    region: "Western",
    tags: ["protein", "dried beef", "panla", "meat"],
    isFeatured: false,
  },
  {
    name: "Dried Goat Meat",
    description:
      "Sun-dried goat meat, lean and full of flavour. A firm favourite in soups. 500g pack.",
    price: 3800,
    unit: "500g",
    productType: "packaged",
    stock: 110,
    categoryName: "Proteins",
    region: "Western",
    tags: ["protein", "dried goat", "meat"],
    isFeatured: false,
  },
  {
    name: "Frozen Tilapia",
    description:
      "Whole frozen tilapia, cleaned and gutted. Sold by weight, kept frozen through delivery.",
    price: 3500,
    unit: "per kg",
    productType: "packaged",
    stock: 90,
    categoryName: "Proteins",
    region: "Western",
    tags: ["protein", "tilapia", "frozen", "fish"],
    isFeatured: false,
  },
  {
    name: "Frozen Catfish",
    description:
      "Fresh-frozen catfish, skinless and cut to order. Rich in flavour for grilling and stews.",
    price: 4000,
    unit: "per kg",
    productType: "packaged",
    stock: 80,
    categoryName: "Proteins",
    region: "Western",
    tags: ["protein", "catfish", "frozen", "fish"],
    isFeatured: false,
  },
  {
    name: "Frozen Mackerel",
    description:
      "Whole frozen mackerel (titus), cleaned and graded. Sold by weight.",
    price: 3000,
    unit: "per kg",
    productType: "packaged",
    stock: 100,
    categoryName: "Proteins",
    region: "South-South",
    tags: ["protein", "mackerel", "titus", "frozen", "fish"],
    isFeatured: false,
  },
  {
    name: "Frozen Beef",
    description:
      "Boneless frozen beef cuts, trimmed and portioned. Sold by weight.",
    price: 4500,
    unit: "per kg",
    productType: "packaged",
    stock: 85,
    categoryName: "Proteins",
    region: "Western",
    tags: ["protein", "beef", "frozen", "meat"],
    isFeatured: false,
  },
  {
    name: "Frozen Goat Meat",
    description:
      "Tender frozen goat meat on the bone, prepared and portioned. Sold by weight.",
    price: 5000,
    unit: "per kg",
    productType: "packaged",
    stock: 70,
    categoryName: "Proteins",
    region: "Western",
    tags: ["protein", "goat", "frozen", "meat"],
    isFeatured: false,
  },
  {
    name: "Frozen Chicken",
    description:
      "Whole dressed frozen chicken, cut to your preference. Sold by weight.",
    price: 4900,
    unit: "per kg",
    productType: "packaged",
    stock: 95,
    categoryName: "Proteins",
    region: "Western",
    tags: ["protein", "chicken", "frozen", "poultry"],
    isFeatured: false,
  },
  {
    name: "Grilled Fish - Fresh",
    description:
      "Whole tilapia marinated in-house and charcoal-grilled to order. Served hot.",
    price: 1500,
    unit: "piece",
    productType: "cooked",
    prepLeadTime: 1,
    maxDailyQty: 60,
    stock: 60,
    categoryName: "Proteins",
    region: "South-South",
    tags: ["protein", "grilled fish", "tilapia", "fresh", "cooked"],
    isFeatured: false,
  },
  {
    name: "Suya (Beef) - Fresh",
    description:
      "Thin beef skewers coated in house yaji and grilled over open flame. Classic Northern street food.",
    price: 1200,
    unit: "piece",
    productType: "cooked",
    prepLeadTime: 2,
    maxDailyQty: 80,
    stock: 80,
    categoryName: "Proteins",
    region: "Northern",
    tags: ["protein", "suya", "beef", "grilled", "fresh", "northern"],
    isFeatured: true,
  },
  {
    name: "Peppered Meat - Fresh",
    description:
      "Tender beef sautéed with fresh peppers, onion and spice. Ready to eat straight from the tub.",
    price: 1500,
    unit: "piece",
    productType: "cooked",
    prepLeadTime: 2,
    maxDailyQty: 70,
    stock: 70,
    categoryName: "Proteins",
    region: "Western",
    tags: ["protein", "peppered meat", "beef", "fresh", "cooked"],
    isFeatured: false,
  },
  {
    name: "Peppered Chicken - Fresh",
    description:
      "Chicken pieces fried then tossed in a spicy pepper sauce. Rich, savoury and ready to eat.",
    price: 2000,
    unit: "piece",
    productType: "cooked",
    prepLeadTime: 2,
    maxDailyQty: 65,
    stock: 65,
    categoryName: "Proteins",
    region: "Western",
    tags: ["protein", "peppered chicken", "poultry", "fresh", "cooked"],
    isFeatured: false,
  },
];
